package model.persistencia.dao.hibernate.beans;
// default package
// Generated 22-ago-2015 18:58:10 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */
public class Estado extends GenericBean implements java.io.Serializable {

	private int idEstado;
	private String descripcion;
	private Set inmuebles = new HashSet(0);

	public Estado() {
	}

	public Estado(int idEstado) {
		this.idEstado = idEstado;
	}

	public Estado(int idEstado, String descripcion, Set inmuebles) {
		this.idEstado = idEstado;
		this.descripcion = descripcion;
		this.inmuebles = inmuebles;
	}

	public int getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(int idEstado) {
		this.idEstado = idEstado;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getInmuebles() {
		return this.inmuebles;
	}

	public void setInmuebles(Set inmuebles) {
		this.inmuebles = inmuebles;
	}

}
