package model.persistencia.dao.hibernate.beans;
// default package
// Generated 22-ago-2015 18:58:10 by Hibernate Tools 4.3.1

/**
 * FotosDetalleInmueble generated by hbm2java
 */
public class FotosDetalleInmueble extends GenericBean implements java.io.Serializable {

	private int idFotosDetalleInmueble;
	private DetalleInmueble detalleInmueble;
	private String ruta;

	public FotosDetalleInmueble() {
	}

	public FotosDetalleInmueble(int idFotosDetalleInmueble) {
		this.idFotosDetalleInmueble = idFotosDetalleInmueble;
	}

	public FotosDetalleInmueble(int idFotosDetalleInmueble,
			DetalleInmueble detalleInmueble, String ruta) {
		this.idFotosDetalleInmueble = idFotosDetalleInmueble;
		this.detalleInmueble = detalleInmueble;
		this.ruta = ruta;
	}

	public int getIdFotosDetalleInmueble() {
		return this.idFotosDetalleInmueble;
	}

	public void setIdFotosDetalleInmueble(int idFotosDetalleInmueble) {
		this.idFotosDetalleInmueble = idFotosDetalleInmueble;
	}

	public DetalleInmueble getDetalleInmueble() {
		return this.detalleInmueble;
	}

	public void setDetalleInmueble(DetalleInmueble detalleInmueble) {
		this.detalleInmueble = detalleInmueble;
	}

	public String getRuta() {
		return this.ruta;
	}

	public void setRuta(String ruta) {
		this.ruta = ruta;
	}

}
