package model.persistencia.dao.hibernate.beans;

// default package
// Generated 22-ago-2015 18:58:10 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * DetalleInmueble generated by hbm2java
 */
public class DetalleInmueble extends GenericBean implements java.io.Serializable {

	private int idDetalleInmueble;
	private Inmueble inmueble;
	private int autor;
	private String comentario;
	private Set fotosDetalleInmuebles = new HashSet(0);

	public DetalleInmueble() {
	}

	public DetalleInmueble(int idDetalleInmueble) {
		this.idDetalleInmueble = idDetalleInmueble;
	}

	public DetalleInmueble(int idDetalleInmueble, Inmueble inmueble, int autor,
			String comentario, Set fotosDetalleInmuebles) {
		this.idDetalleInmueble = idDetalleInmueble;
		this.inmueble = inmueble;
		this.autor = autor;
		this.comentario = comentario;
		this.fotosDetalleInmuebles = fotosDetalleInmuebles;
	}

	public int getIdDetalleInmueble() {
		return this.idDetalleInmueble;
	}

	public void setIdDetalleInmueble(int idDetalleInmueble) {
		this.idDetalleInmueble = idDetalleInmueble;
	}

	public Inmueble getInmueble() {
		return this.inmueble;
	}

	public void setInmueble(Inmueble inmueble) {
		this.inmueble = inmueble;
	}

	public int getAutor() {
		return this.autor;
	}

	public void setAutor(int autor) {
		this.autor = autor;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public Set getFotosDetalleInmuebles() {
		return this.fotosDetalleInmuebles;
	}

	public void setFotosDetalleInmuebles(Set fotosDetalleInmuebles) {
		this.fotosDetalleInmuebles = fotosDetalleInmuebles;
	}

}
