package model.persistencia.dao.hibernate.beans;
// default package
// Generated 22-ago-2015 18:58:10 by Hibernate Tools 4.3.1

/**
 * FotosInmueble generated by hbm2java
 */
public class FotosInmueble extends GenericBean implements java.io.Serializable {

	private int idFotosInmueble;
	private Inmueble inmueble;
	private String ruta;

	public FotosInmueble() {
	}

	public FotosInmueble(int idFotosInmueble) {
		this.idFotosInmueble = idFotosInmueble;
	}

	public FotosInmueble(int idFotosInmueble, Inmueble inmueble, String ruta) {
		this.idFotosInmueble = idFotosInmueble;
		this.inmueble = inmueble;
		this.ruta = ruta;
	}

	public int getIdFotosInmueble() {
		return this.idFotosInmueble;
	}

	public void setIdFotosInmueble(int idFotosInmueble) {
		this.idFotosInmueble = idFotosInmueble;
	}

	public Inmueble getInmueble() {
		return this.inmueble;
	}

	public void setInmueble(Inmueble inmueble) {
		this.inmueble = inmueble;
	}

	public String getRuta() {
		return this.ruta;
	}

	public void setRuta(String ruta) {
		this.ruta = ruta;
	}

}
