package model.persistencia.dao.hibernate.beans;
// default package
// Generated 22-ago-2015 18:58:10 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Inmueble generated by hbm2java
 */
public class Inmueble extends GenericBean implements java.io.Serializable {

	private int idInmueble;
	private Estado estado;
	private Usuarios usuariosByPropietario;
	private Usuarios usuariosByInquilino;
	private String direccion;
	private String ciudad;
	private String codPostal;
	private int metros;
	private Set fotosInmuebles = new HashSet(0);
	private Set detalleInmuebles = new HashSet(0);

	public Inmueble() {
	}

	public Inmueble(int idInmueble) {
		this.idInmueble = idInmueble;
	}
	

	public Inmueble(int idInmueble, String direccion, String ciudad,
			String codPostal, int metros) {
		this.idInmueble = idInmueble;
		this.direccion = direccion;
		this.ciudad = ciudad;
		this.codPostal = codPostal;
		this.metros = metros;
	}

	public Inmueble(int idInmueble, Estado estado,
			Usuarios usuariosByPropietario, Usuarios usuariosByInquilino,
			String direccion, String ciudad, String codPostal, int metros,
			Set fotosInmuebles, Set detalleInmuebles) {
		this.idInmueble = idInmueble;
		this.estado = estado;
		this.usuariosByPropietario = usuariosByPropietario;
		this.usuariosByInquilino = usuariosByInquilino;
		this.direccion = direccion;
		this.ciudad = ciudad;
		this.codPostal = codPostal;
		this.metros = metros;
		this.fotosInmuebles = fotosInmuebles;
		this.detalleInmuebles = detalleInmuebles;
	}
	public Inmueble(int idInmueble, Estado estado,
			Usuarios usuariosByPropietario, Usuarios usuariosByInquilino,
			String direccion, String ciudad, String codPostal, int metros) {
		this.idInmueble = idInmueble;
		this.estado = estado;
		this.usuariosByPropietario = usuariosByPropietario;
		this.usuariosByInquilino = usuariosByInquilino;
		this.direccion = direccion;
		this.ciudad = ciudad;
		this.codPostal = codPostal;
		this.metros = metros;
	}

	public int getIdInmueble() {
		return this.idInmueble;
	}

	public void setIdInmueble(int idInmueble) {
		this.idInmueble = idInmueble;
	}

	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	public Usuarios getUsuariosByPropietario() {
		return this.usuariosByPropietario;
	}

	public void setUsuariosByPropietario(Usuarios usuariosByPropietario) {
		this.usuariosByPropietario = usuariosByPropietario;
	}

	public Usuarios getUsuariosByInquilino() {
		return this.usuariosByInquilino;
	}

	public void setUsuariosByInquilino(Usuarios usuariosByInquilino) {
		this.usuariosByInquilino = usuariosByInquilino;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public String getCodPostal() {
		return this.codPostal;
	}

	public void setCodPostal(String codPostal) {
		this.codPostal = codPostal;
	}

	public int getMetros() {
		return this.metros;
	}

	public void setMetros(int metros) {
		this.metros = metros;
	}

	public Set getFotosInmuebles() {
		return this.fotosInmuebles;
	}

	public void setFotosInmuebles(Set fotosInmuebles) {
		this.fotosInmuebles = fotosInmuebles;
	}

	public Set getDetalleInmuebles() {
		return this.detalleInmuebles;
	}

	public void setDetalleInmuebles(Set detalleInmuebles) {
		this.detalleInmuebles = detalleInmuebles;
	}

	@Override
	public String toString() {
		return "Inmueble [idInmueble=" + idInmueble + ", direccion=" + direccion + ", ciudad=" + ciudad
				+ ", codPostal=" + codPostal + ", metros=" + metros + "]";
	}
	

}
