package model.persistencia.dao.hibernate.beans;
// default package
// Generated 22-ago-2015 18:58:10 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios extends GenericBean implements java.io.Serializable {

	private int idUsuario;
	private TipoUsuario tipoUsuario;
	private String dni;
	private String nombre;
	private String apellido;
	private String email;
	private String password;
	private Set inmueblesForPropietario = new HashSet(0);
	private Set inmueblesForInquilino = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Usuarios(int idUsuario, TipoUsuario tipoUsuario, String dni,
			String nombre, String apellido, String email, String password,
			Set inmueblesForPropietario, Set inmueblesForInquilino) {
		this.idUsuario = idUsuario;
		this.tipoUsuario = tipoUsuario;
		this.dni = dni;
		this.nombre = nombre;
		this.apellido = apellido;
		this.email = email;
		this.password = password;
		this.inmueblesForPropietario = inmueblesForPropietario;
		this.inmueblesForInquilino = inmueblesForInquilino;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public TipoUsuario getTipoUsuario() {
		return this.tipoUsuario;
	}

	public void setTipoUsuario(TipoUsuario tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getInmueblesForPropietario() {
		return this.inmueblesForPropietario;
	}

	public void setInmueblesForPropietario(Set inmueblesForPropietario) {
		this.inmueblesForPropietario = inmueblesForPropietario;
	}

	public Set getInmueblesForInquilino() {
		return this.inmueblesForInquilino;
	}

	public void setInmueblesForInquilino(Set inmueblesForInquilino) {
		this.inmueblesForInquilino = inmueblesForInquilino;
	}

}
